# Generated by Django 4.2.7 on 2025-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avg_consultation_time',
            field=models.PositiveIntegerField(default=30, help_text='平均就诊时间（分钟）'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_daily_patients',
            field=models.PositiveIntegerField(default=50, help_text='每日最大患者数'),
        ),
        migrations.AddField(
            model_name='group',
            name='priority_rules',
            field=models.JSONField(default=dict, help_text='优先级规则'),
        ),
        migrations.AddField(
            model_name='group',
            name='working_hours',
            field=models.JSONField(default=list, help_text='工作时间配置'),
        ),
    ]
